set_property IOSTANDARD LVDS [get_ports fclkp_1]
set_property PACKAGE_PIN AF7 [get_ports fclkp_1]
set_property IOSTANDARD LVDS [get_ports {gth_refClkP_i_1[0]}]
set_property IOSTANDARD LVDS [get_ports {gth_refClkP_i_1[1]}]
set_property PACKAGE_PIN V6 [get_ports {gth_refClkP_i_1[1]}]
set_property PACKAGE_PIN Y6 [get_ports {gth_refClkP_i_1[0]}]
