# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/elmXdc.xdc

# Block Designs: bd/ps_block/ps_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block || ORIG_REF_NAME==ps_block} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_zynq_ultra_ps_e_0_0/ps_block_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ps_block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_axi_gpio_0_0/ps_block_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_axi_gpio_0_0 || ORIG_REF_NAME==ps_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_ps8_0_axi_periph_0/ps_block_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_ps8_0_axi_periph_0 || ORIG_REF_NAME==ps_block_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_rst_ps8_0_96M_0/ps_block_rst_ps8_0_96M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_rst_ps8_0_96M_0 || ORIG_REF_NAME==ps_block_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_clktestTop_1_0/ps_block_clktestTop_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_clktestTop_1_0 || ORIG_REF_NAME==ps_block_clktestTop_1_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_auto_pc_0/ps_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_auto_pc_0 || ORIG_REF_NAME==ps_block_auto_pc_0} -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_zynq_ultra_ps_e_0_0/ps_block_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_zynq_ultra_ps_e_0_0/ps_block_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ps_block_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_axi_gpio_0_0/ps_block_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_axi_gpio_0_0 || ORIG_REF_NAME==ps_block_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_axi_gpio_0_0/ps_block_axi_gpio_0_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_axi_gpio_0_0/ps_block_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_axi_gpio_0_0 || ORIG_REF_NAME==ps_block_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_rst_ps8_0_96M_0/ps_block_rst_ps8_0_96M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_rst_ps8_0_96M_0 || ORIG_REF_NAME==ps_block_rst_ps8_0_96M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_rst_ps8_0_96M_0/ps_block_rst_ps8_0_96M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_rst_ps8_0_96M_0 || ORIG_REF_NAME==ps_block_rst_ps8_0_96M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_rst_ps8_0_96M_0/ps_block_rst_ps8_0_96M_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_auto_pc_0/ps_block_auto_pc_0_ooc.xdc

# XDC: bd/ps_block/ps_block_ooc.xdc
