# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/elmXDC.xdc

# Block Designs: bd/ps_block/ps_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block || ORIG_REF_NAME==ps_block} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_zynq_ultra_ps_e_0_0/ps_block_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ps_block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_ps8_0_axi_periph_0/ps_block_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_ps8_0_axi_periph_0 || ORIG_REF_NAME==ps_block_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_rst_ps8_0_96M_0/ps_block_rst_ps8_0_96M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_rst_ps8_0_96M_0 || ORIG_REF_NAME==ps_block_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_clkTestTop_0_0/ps_block_clkTestTop_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_clkTestTop_0_0 || ORIG_REF_NAME==ps_block_clkTestTop_0_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_xbar_0/ps_block_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_xbar_0 || ORIG_REF_NAME==ps_block_xbar_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_debug_bridge_0_1/ps_block_debug_bridge_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_debug_bridge_0_1 || ORIG_REF_NAME==ps_block_debug_bridge_0_1} -quiet] -quiet

# Block Designs: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/bd_5559.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5559 || ORIG_REF_NAME==bd_5559} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_0/bd_5559_axi_jtag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5559_axi_jtag_0 || ORIG_REF_NAME==bd_5559_axi_jtag_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_1/bd_5559_bsip_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5559_bsip_0 || ORIG_REF_NAME==bd_5559_bsip_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_2/bd_5559_bs_switch_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5559_bs_switch_1_0 || ORIG_REF_NAME==bd_5559_bs_switch_1_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_debug_bridge_1_1/ps_block_debug_bridge_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_debug_bridge_1_1 || ORIG_REF_NAME==ps_block_debug_bridge_1_1} -quiet] -quiet

# Block Designs: bd/ps_block/ip/ps_block_debug_bridge_1_1/bd_0/bd_9508.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9508 || ORIG_REF_NAME==bd_9508} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_debug_bridge_1_1/bd_0/ip/ip_0/bd_9508_xsdbm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9508_xsdbm_0 || ORIG_REF_NAME==bd_9508_xsdbm_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_debug_bridge_1_1/bd_0/ip/ip_1/bd_9508_lut_buffer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9508_lut_buffer_0 || ORIG_REF_NAME==bd_9508_lut_buffer_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_vio_0_0/ps_block_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_vio_0_0 || ORIG_REF_NAME==ps_block_vio_0_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_reg64_0_0/ps_block_reg64_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_reg64_0_0 || ORIG_REF_NAME==ps_block_reg64_0_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_auto_pc_0/ps_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_auto_pc_0 || ORIG_REF_NAME==ps_block_auto_pc_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_auto_ds_0/ps_block_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_auto_ds_0 || ORIG_REF_NAME==ps_block_auto_ds_0} -quiet] -quiet

# IP: bd/ps_block/ip/ps_block_auto_pc_1/ps_block_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_auto_pc_1 || ORIG_REF_NAME==ps_block_auto_pc_1} -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_zynq_ultra_ps_e_0_0/ps_block_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_zynq_ultra_ps_e_0_0/ps_block_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ps_block_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_rst_ps8_0_96M_0/ps_block_rst_ps8_0_96M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_rst_ps8_0_96M_0 || ORIG_REF_NAME==ps_block_rst_ps8_0_96M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_rst_ps8_0_96M_0/ps_block_rst_ps8_0_96M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_rst_ps8_0_96M_0 || ORIG_REF_NAME==ps_block_rst_ps8_0_96M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_rst_ps8_0_96M_0/ps_block_rst_ps8_0_96M_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_xbar_0/ps_block_xbar_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_0/constraints/axi_jtag.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5559_axi_jtag_0 || ORIG_REF_NAME==bd_5559_axi_jtag_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_0/bd_5559_axi_jtag_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_1/constraints/bsip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5559_bsip_0 || ORIG_REF_NAME==bd_5559_bsip_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_1/bd_5559_bsip_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_2/constraints/bs_switch.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5559_bs_switch_1_0 || ORIG_REF_NAME==bd_5559_bs_switch_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/ip/ip_2/bd_5559_bs_switch_1_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_debug_bridge_0_1/bd_0/bd_5559_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_debug_bridge_0_1/ps_block_debug_bridge_0_1_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_debug_bridge_1_1/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9508_xsdbm_0 || ORIG_REF_NAME==bd_9508_xsdbm_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_debug_bridge_1_1/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9508_xsdbm_0 || ORIG_REF_NAME==bd_9508_xsdbm_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_debug_bridge_1_1/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9508_xsdbm_0 || ORIG_REF_NAME==bd_9508_xsdbm_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_debug_bridge_1_1/bd_0/ip/ip_0/bd_9508_xsdbm_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_debug_bridge_1_1/bd_0/bd_9508_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_debug_bridge_1_1/ps_block_debug_bridge_1_1_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_vio_0_0/ps_block_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_block_vio_0_0 || ORIG_REF_NAME==ps_block_vio_0_0} -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_vio_0_0/ps_block_vio_0_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_auto_pc_0/ps_block_auto_pc_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_auto_ds_0/ps_block_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_block_auto_ds_0 || ORIG_REF_NAME==ps_block_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ps_block/ip/ps_block_auto_ds_0/ps_block_auto_ds_0_ooc.xdc

# XDC: bd/ps_block/ip/ps_block_auto_pc_1/ps_block_auto_pc_1_ooc.xdc

# XDC: bd/ps_block/ps_block_ooc.xdc
